
locale                   : "en-US"
title                    : "Ali Vardasbi"
title_separator          : "-"
name                     : &name "Ali Vardasbi"
description              : &description "personal page"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "enabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page


author:
  name             : "Ali Vardasbi"
  avatar           : "files/Ali.jpg"
  # bio              : ""
  location         : "Amsterdam, The Netherlands"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=chzcQgMAAAAJ"
  email            : "<myfullname>@gmail.com"
  github           : "AliVard"
  linkedin         : "ali-vardasbi-44548844/"
  stackoverflow    : # http://stackoverflow.com/users
  twitter          : "@AliVardasbi"


markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Amsterdam # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

